kodi-game/kodi-game-scripting

kodi_game_scripting/config.py

I'm guessing this is right from seeing https://github.com/libretro/Genesis-Plus-GX

config: Fix genplus makefile name

---

templates/addon/game.libretro.{{ game.name }}/addon.xml.in.j2

In the Game API v1.0.36, support was added for a topology.xml file that describes the ports on the virtual console. Mouse and keyboard are included in the topology, so they are no longer needed in addon.xml.
For https://github.com/xbmc/xbmc/pull/13499.

Remove <supports_mouse> and <supports_keyboard> from addon.xml

---

templates/addon/depends/windows/mingw/01-make.bat.in.patch
templates/addon/depends/windows/mingw/02-MinGWConfig.cmake.in.patch
templates/addon/depends/windows/mingw/CMakeLists.txt
templates/addon/depends/windows/mingw/mingw.txt

MSYS/MinGW was removed from Kodi (except for some ffmpeg stuff), so we need to provide MinGW in our add-ons.
Tested with 2048 and Snes9x on Windows.
In the future, it would be nice to allow custom CMake on windows so that we can build with MSVCC instead of MinGW for debug symbols: https://github.com/Rechi/game.libretro.2048/commit/8cf215b
Imported from: https://github.com/kodi-game/game.libretro.2048/compare/master...Rechi:addFUCKINGstupidMingwBuildSystemInsteadOfMSVCwithDebugSymbols

Add MinGW build system to windows depends

---

kodi_game_scripting/config.py

Include chailove to automatically keep the game addon up to date.
This requires: https://github.com/kodi-game/game.libretro.chailove/pull/2 to be merged first.
Unfortunately also the debug build needs to be fixed first (there are undefined symbols that prevent us from loading the compiled lib within the script).
```
vendor/freetype2/src/gzip/ftgzip.o: In function `inflate_codes_new': chailove/vendor/freetype2/src/gzip/infcodes.c:74: undefined reference to `z_verbose'
vendor/freetype2/src/gzip/ftgzip.o: In function `inflate_codes': chailove/vendor/freetype2/src/gzip/infcodes.c:129: undefined reference to `z_verbose'
chailove/vendor/freetype2/src/gzip/infcodes.c:150: undefined reference to `z_verbose'
chailove/vendor/freetype2/src/gzip/infcodes.c:165: undefined reference to `z_verbose' …
```

config: Add chailove

---

templates/addon/.travis.yml.j2
templates/addon/README.md.j2
templates/addon/appveyor.yml.j2

This generates the READMEs and CI configs and fixes:
- All links to the Travis CI build status badges.
- The Travis CI builds that fail on osx/xcode6.4 with "ld: library not found for -lgcc_s.10.4" by disabling that job.
- Some c&p errors for build status badge links.
- Project names in the README.
There are a few projects where the Appveyor status badge doesn't point to kodi-game:
@garbear / @notspiff Could you please move the project in Appveyor over to kodi-game?
New projects where we need to enable Travis CI/Appveyor.
Generated patch:
```
commit 0c29b6c1c899ff6048bad8d02600b93329aed8bc
Author:     Christian Fetzer <fetzer.ch@gmail.com>
AuthorDate: Thu Mar 8 22:08:00 2018 +0100
Commit:     Christian Fetzer <fetzer.ch@gmail.com>
CommitDate: Thu Mar 8 22:08:00 2018 +0100
Updated by …
```

templates: Add README.md, .travis.yml & appveyor.yml

---

kodi_game_scripting/git_access.py

kodi-game-scripting/kodi_game_scripting/git_access.py:50:
DeprecationWarning: Call to deprecated function (or staticmethod) rate.
(
The rate object is deprecated. If you're writing new API client code
or updating existing code, you should use the core object instead of
the rate object. The core object contains the same information that
is present in the rate object.
)
rate = self._github.get_rate_limit().rate

git_access: Switch from rate to core in GitHub API

---

requirements.txt

The change from rate to core in 1f7a29f only works when using an up to
date PyGithub version.

git_access: Make sure we have a supported PyGithub version installed

---

templates/addon/.travis.yml.j2

Please push updates to desmume, mame2016, mupen64plus and reicast (without version bump and tagging) after merging this PR.

templates: install libgl1-mesa-dev on Travis CI if GL is used

---

templates/addon/{{ game.addon }}/resources/language/English/strings.po.j2
tests/integration/test_data/test_template_processor/addon/game.libretro.mygame/resources/language/English/strings.po

Fixes the trailing newlines the right way. #16 was reverted as most editors automatically add a new line at the end of file.

templates: fix trailing newlines in strings.po

---

kodi_game_scripting/process_game_addons.py

- for APP_STL gnustl_static, gnustl_shared, stlport_static and stlport_shared are not supported
- for NDK_TOOLCHAIN_VERSION 4.9 is not unsupported
This extends the android upstream configuration check added at #44.

process_game_addons: exclude more android configurations

---

.travis.yml
templates/addon/{{ game.addon }}/addon.xml.in.j2

The behaviour of re.sub was changed in [bpo-32308](https://bugs.python.org/issue32308).

templates: fix regex_replace for Python 3.7

---

templates/addon/CMakeLists.txt.j2
templates/addon/depends/common/{{ game.name }}/CMakeLists.txt.j2
templates/addon/depends/windows/mingw/CMakeLists.txt.j2
tests/integration/test_data/test_libretro_ctypes/CMakeLists.txt
tests/integration/test_data/test_template_processor/addon/CMakeLists.txt
tests/integration/test_data/test_template_processor/addon/depends/common/mygame/CMakeLists.txt
tests/integration/test_data/test_template_processor/addon/depends/windows/mingw/CMakeLists.txt

https://github.com/xbmc/xbmc/pull/16458 needs a minimum of version of 3.3.
Ubuntu Xenial (16.04) provides CMake 3.5.1 (https://packages.ubuntu.com/xenial/cmake).

templates: set minimum required CMake version to 3.5

---

requirements.txt

When missing, this caused the following error:
```
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint(name='pyfs', value='keyrings.alt.pyfs', group='keyring.backends').
```
After `pip3 install -r requirements.txt`, the script ran successfully.
Borrowed from: https://github.com/dcos/dcos-e2e/pull/1812

Add missing keyrings.alt dependency to requirement.txt

---

kodi_game_scripting/config.py

This updates the emulators in config.py.
Results have been pushed to https://github.com/kodi-game
Two emulators were renamed:
* Reicast -> Flycast
* FBAlpha -> FBNeo
What needs to be updated for these renames?
Beetle NGP failed to build and needed this change: https://github.com/libretro/beetle-ngp-libretro/pull/90
Lutro currently fails to build due to this PR: https://github.com/libretro/libretro-lutro/pull/131
Tested by running `process_game_addons.py`. Observed a process time of 25 mins on a Core i7.

Update emulator configs

---

kodi_game_scripting/config.py

Noticed the following error in the build log:
```
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:49 (file):
file INSTALL cannot find
"/home/garrett/Documents/kodi-game-scripting/game-addons/build/build/4do/src/4do/./4do_libretro.so".
```
Further inspection leads to https://github.com/libretro/opera-libretro/pull/139.
Result: https://github.com/kodi-game/game.libretro.opera/commit/0a47255d42f1a2b44ec6b877c4ac6a61890f258a

config: Rename 4DO to Opera

---

templates/addon/{{ game.addon }}/addon.xml.in.j2

If a libretro author is available, use that instead of "Libretro".
Example update: https://github.com/kodi-game/game.libretro.bluemsx/commit/testing

Use libretro author if available

---

templates/addon/{{ game.addon }}/addon.xml.in.j2

Follow up to https://github.com/kodi-game/kodi-game-scripting/pull/72. Author strings can look like:
```
provider-name="Guillaume Duhammel|Theo Berkau|Anders Montonen">
```
After this change, they look like:
```
provider-name="Guillaume Duhammel, Theo Berkau, Anders Montonen">
```
See https://github.com/kodi-game/game.libretro.yabause/commit/66b4031c76c5cc1a525c4220210022378fa3daba

Replace | with , in libretro author list

---

kodi_game_scripting/config.py
kodi_game_scripting/git_access.py

Every PR I've opened but one is red. I'll shove this in and rebase the others so we can be swimming in a beautiful ocean of green check marks.
Before, pylint errors causing CI failure:
```
__________________ [pylint] kodi_game_scripting/git_access.py __________________
W: 67,12: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
____________________ [pylint] kodi_game_scripting/config.py ____________________
E: 21, 0: Bad option value 'bad-whitespace' (bad-option-value)
```
After, no pylint errors occur and CI succeeds.

Fix pylint errors causing CI failures

---

kodi_game_scripting/config.py

Mupen64Plus was forked. The new repo is https://github.com/libretro/mupen64plus-libretro-nx
I renamed the game.libretro.mupen64plus repo to create a 302 redirect. I renamed the files and folders so that subsequent kodi-game-scripting updates would modify the correct files.
After that, I pointed kodi-game-scripting at the repo, and checked the results.
Successful update by kodi-game-scripting running in an azure pipeline: https://github.com/kodi-game/game.libretro.mupen64plus-nx/commits/master
(build time was about 3 mins)

Add Mupen64Plus-Next to config

---

kodi_game_scripting/config.py

I added config lines for most of the remaining cores at https://github.com/libretro.
Game add-ons on the kodi-game org have been created and are up-to-date. I added summaries on all the repo pages. I set the URLs of all newly created repo pages to the upstream libretro repos.
Adds the following cores:
- 3D Engine
- 81/EightyOne (Sinclair - ZX 81)
- Atari800 (Atari - 5200)
- BK (Soviet BK-0010/0011/Terak 8510a emulator)
- BlastEm (Sega - Mega Drive - Genesis)
- boom3 (Doom 3)
- Cannonball
- Craft (Minecraft clone)
- CrocoDS (Amstrad - CPC)
- Daphne (Arcade)
- Desmume 2015 (Nintendo DS emulator)
- dosbox-core
- ECWolf (Wolfenstein 3D engine)
- FreeChaF (Fairchild ChannelF emulator)
- FreeIntv (Mattel Intellivision emulator)
- Frodo (C64 emulator)
- gameplaySP (GBA emulator)
- HBMAME (Home …

Add 33 new cores from libretro org

---

kodi_game_scripting/process_game_addons.py

As title says.
According to @KOPRajs [here](https://github.com/kodi-game/game.libretro.pcsx-rearmed/issues/19#issuecomment-844994685):
```
Regarding the order of the settings:
It seems we are currently reordering the original options order from libretro to alphabet order. I don't think it is a good idea. The order in the libretro makes sense as related options are kept together.
It seems it is done on line 329 in this file: https://github.com/kodi-game/kodi-game-scripting/blob/master/kodi_game_scripting/process_game_addons.py
I'd suggest to simply remove the "sorted" function and keep the libretro default order.
```
I tried removing `sorted`, and it looks like settings are now in their original order.
Required by https://github.com/kodi-game/kodi-game-scripting/pull/86
Tested as part of …

Don't sort settings by ID

---

templates/addon/depends/windows/mingw/03-use-curl.patch.j2

I noticed that almost all windows builds were failing to download msys during CI runs. @phunkyfish pointed me to his solution: https://github.com/xbmc/inputstream.ffmpegdirect/commit/13ccd30485f8781e437e8f09d5e31e62a04f8661, part of https://github.com/xbmc/inputstream.ffmpegdirect/pull/83.
So let's apply that here.
Before: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-game%2Fgame.libretro.yabause/detail/master/64/pipeline/
After: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-game%2Fgame.libretro.yabause/detail/master/65/pipeline/
I've observed about 10 more successful runs since then with no failures, so I'll push this out to the fleet of add-ons.

Use curl for mingw package downloads

---

kodi_game_scripting/config.py

After messing with dependencies I got dolphin to build, and pushed the latest to game.libretro.dolphin. Let's enable dolphin in config.py so that the script keeps the repo up-to-date.
Blue Ocean view: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-game%2Fgame.libretro.dolphin/detail/13.0.0.2-Matrix/1/pipeline/

Enable dolphin in config.py

---

templates/addon/depends/common/{{ game.name }}/{{ game.name }}.txt.j2

On some platforms, pcem fails on Jenkins with the following error:
```
-- extracting...
src='download/1955c2127990cfdf4c594b35b466e8503d626fa7.zip'
dst='pcem/src/pcem'
-- extracting... [tar xfz]
CMake Error: Problem with archive_read_next_header(): Pathname cannot be converted from UTF-8 to current locale.
CMake Error: Problem extracting tar: download/1955c2127990cfdf4c594b35b466e8503d626fa7.zip
```
Link to CI run: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-game%2Fgame.libretro.pcem/detail/master/54/pipeline/232
I also noticed this for other cores, but forget which ones.
We should fix the extension for all cores, because zips are a no-go for our dependency stuff.
Unfortunately, we detect the extension change as a hash change and bump the version, so this will cause a heavy CI …

Switch to .tar.gz archives for libretro core sources

---

templates/addon/{{ game.addon }}/addon.xml.in.j2

This PR exposes the GL requirement to the Game API, as seen in the wiki: https://kodi.wiki/view/Game_add-ons#Libretro_cores
Unused in Kodi as of yet but we may as well expose it now, to inform readers of addon.xml whether the core is GL-compatible, and later we can show a custom message in Kodi's GUI.
Tested with yabause: https://github.com/kodi-game/game.libretro.yabause/commit/c09aba3cc28fed8abf49f1c170f7cac08ce14a51

Add `requires_opengl` tag to addon.xml.in

---

kodi_game_scripting/template_processor.py
templates/addon/{{ game.addon }}/addon.xml.in.j2

This PR overrides the XML escaping to avoid conflicts with the sync language script.
Jinja seems to escape XML with numeric references, presumably to handle the wider array of HTML escape sequences.
To make generation consistent with the translation sync workflow, we'll implement our own custom XML escaper that handles the five relevant characters.
Full run of add-ons with this change:
https://dev.azure.com/themagnificentmrb/kodi-game-scripting/_build/results?buildId=680&view=logs

Fix escaping XML using numeric references instead of named references

---

templates/addon/depends/windows/mingw/03-use-curl.patch.j2
templates/addon/depends/windows/mingw/CMakeLists.txt.j2
templates/addon/depends/windows/mingw/mingw.sha256.j2
templates/addon/depends/windows/mingw/mingw.txt.j2

In pursuit of solving our sporadic Windows failures (due to bad mirror while downloading msys2 package), I updated msys2 to the latest version on our mirrors.
We'll need some packages for gcc uploaded to our mirrors. In the meantime, I pointed pacman at the msys2 servers instead of our mirrors. This fixes download issues. Not sure if we should upload gcc packages to our mirrors and re-introduce the reason for the download errors in the first place.
Run of all add-ons: https://dev.azure.com/themagnificentmrb/kodi-game-scripting/_build/results?buildId=707&view=results

Update to msys2 2021-07-25

---

templates/addon/Jenkinsfile.j2

Drops tvos-aarch64 from `Jenkinsfile` because it's failing for many cores.
For all the tvos cores that previously succeeded to build for tvos, they'll remain on the mirrors for testing. They won't need updates for a while.

Drop tvos-aarch64 platform from Jenkins

---

.azure/azure-process-addon.yml
azure-pipelines.yml
kodi_game_scripting/process_game_addons.py

This PR adds an azure pipeline YML to run the `process_game_addons.py` script.
Template parameters are used to build each game add-on in a separate step. This lets CI logs display how much time individual add-ons took to build.
Currently, the script triggers on master. This should be changed to a cron job, possibly daily compiles and weekly pushes.
@AlwinEsch can we host it on a kodi azure account?
The total build time is unknown, but probably several hours. When testing with my personal Azure account, I have to disable 1/3 of the cores to stay under the 1hr limit. Most cores are quick, with some  outliers:
* FBNeo: 6 mins
* MAME 2010: 12 mins
* MAME 2015: 25 mins
* MAME 2016: 43 mins
* MAME: times out after 1hr
* ScummVM: 22 mins
I enabled every core and triggered a run that will time …

Set up CI with Azure Pipelines

---

templates/addon/README.md.j2

This PR gives the emulator artwork in the README (added in https://github.com/kodi-game/kodi-game-scripting/pull/103) an alt text that can be indexed by Google, allowing for the artwork to be discoverable in Google image search.
I had the idea when I was searching for icons for the remaining cores. Some of the results were icons on the documentation pages of other projects. It'd be cool if our artwork can be used in the same way.
I tested 2048 because it has all available 
Commit: https://github.com/kodi-game/game.libretro.2048/commit/9555a69aec1f08174a5b6edb331a8b5c2e70d9a9
Before:
```html
```
After:
```html
```
I tested Reminiscence because it has a more complicated add-on name than "2048".
Commit: https://github.com/kodi-game/game.libretro.reminiscence/commit/8094b847c1af754e96122b2b411 …

Add add-on name to README image alt texts for SEO

---

kodi_game_scripting/process_game_addons.py
templates/addon/Jenkinsfile.j2

As title says, this freezes the `Matrix` add-ons at their last round of translation/icon updates in late-January, and moves all add-ons to the `Nexus` branch.
Required to fix Android and macOS builds when the Android builder migrated to ndk 21b in the last few weeks.
Before, failed Jenkins run: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-game%2Fgame.libretro.fceumm/detail/0.0.1.42-Matrix/1/pipeline
After, successful Jenkins run: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-game%2Fgame.libretro.fceumm/detail/master/122/pipeline

Use Nexus branch for Jenkins

---

kodi_game_scripting/process_game_addons.py

While splitting the Vice cores I noticed that when the add-on name/version changed, the summary wasn't updated - it uses the existing summary string instead of "generating" a new one with the up-to-date name and version.
However, even sporadic string updates can wreak havoc on an unsuspecting weblate, so best to remove version from the summary string entirely.
In the process of rolling out to all add-ons.
Example commits:
* kodi-game-scripting update: https://github.com/kodi-game/game.libretro.yabause/commit/f0f862ca961dc8e037106e500130d06cf7ced549
* weblate update - https://github.com/kodi-game/game.libretro.yabause/commit/5cce0c0ba354aa696b22daabafc7d09daf5298f8
* Sync workflow update - https://github.com/kodi-game/game.libretro.yabause/commit/962e30b5ddc4206fe5e9d78d1db64e33ef1d872f

Remove version from summary

---

azure-pipelines.yml
kodi_game_scripting/config.py

Adds new beetle-psx-hw core.
See comment here: https://github.com/kodi-game/game.libretro.beetle-psx/pull/19#issuecomment-1529992242
CI run: https://dev.azure.com/themagnificentmrb/kodi-game-scripting/_build/results?buildId=1182&view=logs&j=b724a4ce-d971-5e6e-9f98-76134d834be3
Generated https://github.com/kodi-game/game.libretro.beetle-psx-hw

Add beetle-psx-hw core

---

kodi_game_scripting/process_game_addons.py
templates/addon/{{ game.addon }}/resources/language/resource.language.en_gb/strings.po.j2
templates/addon/{{ game.addon }}/resources/settings.xml.j2

Previously, when a string in the middle of the settings changed, all subsequent strings would get new IDs, wreaking havoc on weblate.
Now, string IDs are preserved, and new strings are added to the end of strings.po.
Tested with UAE, see success: https://github.com/kodi-game/game.libretro.uae/commit/testing
Another success with vice_x64: https://github.com/kodi-game/game.libretro.vice_x64/commit/70a16dcdfe18ed2fc84dcc0250cd75fc14f25824

Preserve string IDs

---

azure-pipelines.yml
kodi_game_scripting/config.py

This PR adds the yabasanshiro core, based on yabause. Requested here: https://github.com/kodi-game/game.libretro/issues/97
I got it to build and generate the add-on files correctly. However, I'll hold off on adding it to jenkins and the mirrors until we have OpenGL support.
Generated https://github.com/kodi-game/game.libretro.yabasanshiro

Add yabasanshiro core

---

kodi_game_scripting/config.py

As title says, this switches back from the wrapper to the libretro upstream.
Requires https://github.com/kodi-game/game.libretro.scummvm/pull/27
ScummVM originally worked when it was introduced at version 1.8.0 in 2016 in https://github.com/kodi-game/game.libretro.scummvm/pull/1
In 2021, I got themes and extras to work: https://github.com/kodi-game/game.libretro.scummvm/pull/25
In 2023, I updated ScummVM from v2.6 to v2.7, and switched it to use a libretro wrapper repo introduced to wrap the latest scummvm: https://github.com/kodi-game/kodi-game-scripting/pull/115
However, the wrapper repo was discontinued and has been deleted, so we can't even build scummvm anymore.
CI run: https://dev.azure.com/themagnificentmrb/kodi-game-scripting/_build/results?buildId=1519&view=results

Update scummvm to master branch

---

templates/addon/depends/common/{{ game.name }}/CMakeLists.txt.j2

Currently, many cores generate arm binaries when building for intel on macos.
This PR applies the de-facto flags used by libretro to set macOS build flags.
CC @fuzzard

Fix building for Intel macs

---

templates/addon/CMakeLists.txt.j2

Set CMAKE_CXX_STANDARD to 17 in the addon root CMakelists.txt to override master forcing c++20.
CC @fuzzard

Fix building add-ons with Kodi using C++20

---

templates/addon/depends/common/{{ game.name }}/CMakeLists.txt.j2

This PR adds the `APP_SHORT_COMMANDS` variable for Android to get around the ar command being too long.
Before:
```
[arm64-v8a] SharedLibrary : libretro.so
make[8]: /home/jenkins/android-tools/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++: Argument list too long
```
After:
```
[arm64-v8a] SharedLibrary  : libretro.so
[arm64-v8a] Install        : libretro.so => arm64-v8a/libretro.so
[ 87%] No install step for 'scummvm'
[100%] Completed 'scummvm'
[100%] Built target scummvm
```

Fix building ScummVM on Android

---

templates/addon/depends/common/{{ game.name }}/CMakeLists.txt.j2

This PR modifies the core's CMakeLists.txt file to add the parallel -j flag to the build command.
Credit to @fuzzard.
Ran locally on my workstation:
```
[ 29%] Performing configure step for 'scummvm'
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using 16 threads deduced by ProcessorCount
-- Configuring done
-- Generating done
```
* …

Build cores in parellel

---

kodi_game_scripting/config.py

This PR excludes the  `android-armv7` platform from vba-next due to a build error.
Build error was:
```
/ndk-release-r21/bionic/libc/bionic/locale.cpp:136: error: undefined reference to 'operator new(unsigned int)'
/ndk-release-r21/bionic/libc/bionic/locale.cpp:140: error: undefined reference to 'operator delete(void*)'
/ndk-release-r21/bionic/libc/bionic/locale.cpp:155: error: undefined reference to 'operator new(unsigned int)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
After applying the patch, vba-next goes green on all other supported platforms: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-game%2Fgame.libretro.vba-next/detail/master/143/pipeline

config: Excluded 'android-armv7' platform from vba-next

---

templates/addon/{{ game.addon }}/resources/language/resource.language.en_gb/strings.po.j2
templates/addon/{{ game.addon }}/resources/settings.xml.j2

This PR renames the main (and only) settings category from "Settings" to "General".
"Settings"  already appears on the screen in the dialog title. "General" is a better label and is more consistent with the rest of Kodi.
Noticed by @jjd-uk here: https://github.com/xbmc/xbmc/pull/25598#issuecomment-2296998113
I modified a local add-on by hand. Tested in the Advanced Settings in-game dialog.
Before:
After:
I ran the Azure CI script on Yabause and it pushed a new version (0.9.15.61) to the repo. Jenkins picked up the new version and uploaded binaries to the mirrors. Tested in the add-on browser.
Before:
TODO
After:
TODO: Take a screenshot when the update deploys in 24 hr

Rename single settings category from "Settings" to "General"

---

kodi_game_scripting/config.py

Fixes https://github.com/kodi-game/game.libretro.swanstation/issues/2
CI run: https://dev.azure.com/themagnificentmrb/kodi-game-scripting/_build/results?buildId=1847&view=results

Change swanstation to kodi-game org repo
